apisix:
  node_listen:
    - port: 9080 # Existing HTTP port
#    - port: 443  # HTTPS port
#      enable_http2: true
#      enable_ssl: true
  ssl:
    enable: true
    listen:
      - port: 443
        enable_http2: true
    ssl_protocols: TLSv1.2 TLSv1.3
# ssl_protocols: TLSv1.2 TLSv1.3 TLSv1 TLSv1.1 TLSv1.2
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false              #  disable ssl_session_tickets by default for 'ssl_session_tickets' would make Perfect Forward Secrecy useless.
                                            #  ref: https://github.com/mozilla/server-side-tls/issues/135
    key_encrypt_salt:             #  If not set, will save origin ssl key into etcd.
      - edd1c9f0985e76a2          #  If set this, the key_encrypt_salt should be an array whose elements are string, and the size is also 16, and it will encrypt ssl key with AES-128-CBC
                                  #  !!! So do not change it after saving your ssl, it can't decrypt the ssl keys have be saved if you change !!
                                  #  Only use the first key to encrypt, and decrypt in the order of the array.

    #fallback_sni: "my.default.domain"      # If set this, when the client doesn't send SNI during handshake, the fallback SNI will be used instead
    enable_control: true
    ssl_certificate: "/etc/ssl/certs/youwinndigitalfullchain.pem"
    ssl_certificate_key: "/etc/ssl/private/youwinndigital.key"
  router:
    http: radixtree_host_uri         # radixtree_uri: match route by uri(base on radixtree)

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    admin_key:
      - name: admin
        key: ")ypl+=SrcflCB4|^su91"  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
    allow_admin:
    - 140.228.55.28/32